Repeka\Domain\Entity\Metadata:
  type: entity
  table: metadata
  repositoryClass: Repeka\Application\Repository\MetadataDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    control:
      type: string
      length: 25
    name:
      type: string
      length: 255
    label:
      type: json_document
      options: {jsonb: true}
    description:
      type: json_document
      options: {jsonb: true}
    placeholder:
      type: json_document
      options: {jsonb: true}
