imports:
  - { resource: config.yml }

framework:
  profiler:
    only_exceptions: false
    collect: true
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true

monolog:
  handlers:
    main:
      action_level: notice
    main_nested:
      max_files: 5

web_profiler:
  intercept_redirects: false
  toolbar: true
