imports:
    - { resource: security.yml }

doctrine:
  dbal:
    driver: pdo_pgsql
    host: localhost
    dbname: repeka
    user: repeka
    password: repeka
  orm:
    auto_mapping: true

doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Repeka\Migrations

framework:
  assets: ~
  csrf_protection: ~
  default_locale: "%locale%"
  form: ~
  fragments: ~
  http_method_override: true
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session:
    handler_id: session.handler.native_file
    save_path: "%kernel.cache_dir%/../../sessions/%kernel.environment%"
  templating:
    engines:
      - twig
  trusted_hosts: ~
  trusted_proxies: ~
  validation:
    enable_annotations: true

lexik_jwt_authentication:
  private_key_path: "%kernel.root_dir%/../var/jwt/private.pem"
  public_key_path: "%kernel.root_dir%/../var/jwt/public.pem"
  pass_phrase: ~
  token_ttl: 86400
  token_extractors:
    cookie:
      enabled: true
      name: '%jwt_cookie_name%'

parameters:
  locale: pl
  jwt_cookie_name: 'bearer'
  secret: some_secret

swiftmailer:
  host: "127.0.0.1"
  password: ~
  spool:
    type: memory
  transport: smtp
  username: ~

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"

fake_module:
  admin_emails_reply_to:
    - first@test.pl
    - second@test.pl
