imports:
  - { resource: security.yml }
  - { resource: metrics.yml }
  - { resource: config_build.yml}

repeka:
  default_ui_language: pl
  supported_controls:
    - text
    - textarea
    - integer
    - date
    - boolean
    - relationship
    - file

  metadata_nesting_depth: 3
  elasticsearch:
    host: elasticsearch
    index_name: repeka
    analyzers:
      en: english
      de: german
  upload_dir: "%kernel.root_dir%/../var/uploads"

doctrine:
  dbal:
    driver: pdo_pgsql
    host: postgres
    dbname: repeka
    user: postgres
    password: repeka
  orm:
    auto_mapping: false
    mappings:
      RepekaBundle:
        type: yml
        prefix: Repeka\Application\Entity
        dir: "%kernel.root_dir%/../src/Repeka/Application/Resources/config/doctrine/bundle"
        # when the is_bundle is set to false, mapping files can be placed in other than default directory
        # (in this case it is config/doctrine/bundle instead of the default config/doctrine)
        # https://symfony.com/doc/current/reference/configuration/doctrine.html#is-bundle
        is_bundle: false
      RepekaDomain:
        type: yml
        prefix: Repeka\Domain\Entity
        dir: "%kernel.root_dir%/../src/Repeka/Application/Resources/config/doctrine/domain"
        is_bundle: false

doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Repeka\Migrations

framework:
  assets: ~
  csrf_protection: ~
  default_locale: "%locale%"
  form:
    csrf_protection:
      enabled: false
  fragments: ~
  http_method_override: true
  profiler:
    collect: false
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  serializer:
    enabled: true
  session:
    handler_id: session.handler.native_file
    save_path: "%kernel.cache_dir%/../../sessions/%kernel.environment%"
  templating:
    engines:
      - twig
  trusted_hosts: ~
  trusted_proxies: ~
  validation:
    enable_annotations: true

parameters:
  locale: pl
  secret: some_secret

swiftmailer:
  host: "127.0.0.1"
  password: ~
  spool:
    type: memory
  transport: smtp
  username: ~

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    application_version: "%application_version%"
