imports:
  - { resource: security.yml }
  - { resource: metrics.yml }
  - { resource: config_build.yml}

data_module:
  supported_controls:
    - text
    - textarea
    - int
    - double
    - date
    - daterange
    - boolean
  supported_languages:
    - PL
    - EN
    - DE

doctrine:
  dbal:
    driver: pdo_pgsql
    host: localhost
    dbname: repeka
    user: repeka
    password: repeka
  orm:
    auto_mapping: false
    mappings:
      DataModuleBundle:
        type: yml
        prefix: Repeka\DataModule\Domain\Entity
        dir: %kernel.root_dir%/../src/Repeka/DataModule/Bundle/Resources/config/doctrine
        is_bundle: false
      UserModuleBundle:
        type: yml
        prefix: Repeka\UserModule\Domain\Entity
        dir: %kernel.root_dir%/../src/Repeka/UserModule/Bundle/Resources/config/doctrine
        is_bundle: false

doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Repeka\Migrations

framework:
  assets: ~
  csrf_protection: ~
  default_locale: "%locale%"
  form:
    csrf_protection:
      enabled: false
  fragments: ~
  http_method_override: true
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  session:
    handler_id: session.handler.native_file
    save_path: "%kernel.cache_dir%/../../sessions/%kernel.environment%"
  templating:
    engines:
      - twig
  trusted_hosts: ~
  trusted_proxies: ~
  validation:
    enable_annotations: true

parameters:
  locale: pl
  secret: some_secret

swiftmailer:
  host: "127.0.0.1"
  password: ~
  spool:
    type: memory
  transport: smtp
  username: ~

twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
  globals:
    application_version: "%application_version%"
