imports:
  - { resource: config.yml }

monolog:
  handlers:
    console:
      type: console
    main:
      action_level: error
      handler: main_nested
      type: fingers_crossed
    main_nested:
      channels: ['!exception_listener']
      level: debug
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      type: stream
    exception_listener:
      channels: ['exception_listener']
      level: debug
      path: "%kernel.logs_dir%/%kernel.environment%-exception.log"
      type: stream
      formatter: Monolog\Formatter\LineFormatter
