imports:
  - { resource: config_dev.yml }

doctrine:
  dbal:
    dbname: repeka_integration_testing

framework:
  profiler:
    collect: false
  session:
    storage_id: session.storage.mock_file
  test: ~

monolog:
  handlers:
    main:
      channels: ['!event', '!exception_listener']
      level: notice
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      type: stream

repeka:
  resource_classes:
    - name: books
      admins:
        - Username: admin
      operators:
        - Username: budynek
    - name: dictionaries
      admins:
        - Username: admin
    - name: users
      admins:
        - Username: admin
    - name: cms
  templating:
    templates_resource_class: cms
  expose_endpoints:
    /about:
      metadata: wyrenderowana_tresc_strony
      resourceId: 18
    /resources-title/{resourceId}:
      metadata: tytul
  elasticsearch:
    index_name: repeka-testing

web_profiler:
  intercept_redirects: false
  toolbar: false

security:
  firewalls:
    main:
      http_basic: ~

m6_statsd:
  servers:
    default:
      address: 'udp://localhost'

services:
  test.client:
    class: Repeka\Tests\TestClient
    shared: false
    public: true
    arguments:
      - '@kernel'
      - '%test.client.parameters%'
      - '@test.client.history'
      - '@test.client.cookiejar'
  Repeka\Application\Authentication\PKSoapService:
    class: Repeka\Tests\Integration\Authentication\TestPKSoapService

twig:
  cache: false
