imports:
  - { resource: config.yml }

framework:
  profiler:
    only_exceptions: false
    collect: true
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true

monolog:
  handlers:
    console:
      channels: ['!event', '!doctrine']
      type: console
    main:
      channels: ['!event', '!exception_listener']
      level: notice
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      type: rotating_file
    exception_listener:
      channels: ['exception_listener']
      level: notice
      path: "%kernel.logs_dir%/%kernel.environment%-exception.log"
      type: rotating_file
      formatter: Monolog\Formatter\LineFormatter

parameters:
  use_webpack_dev_server: true

web_profiler:
  intercept_redirects: false
  toolbar: true
