imports:
  - { resource: security.yml }
  - { resource: metrics.yml }
  - { resource: config_build.yml}
  - { resource: postgres_json_functions.yml }

repeka:
  default_ui_language: pl
  fallback_ui_languages: [pl, en]

  resource_classes: []

  metadata_nesting_depth: 3
  elasticsearch:
    host: elasticsearch
    index_name: repeka
    analyzers:
      en: english
      de: german

  upload_dirs:
    - id: resourceFiles
      label: Pliki zasobu
      # resource with ID=123 will have var/uploads/i1/i2/i3/r123
      path: '%kernel.root_dir%/../var/uploads/{{resource.id|split("")|wrap("i","/")|join}}r{{resource.id}}'
    - id: commonResourceClass
      label: Wspólne pliki klasy zasobu
      path: '%kernel.root_dir%/../var/uploads/common-{{resource.resourceClass}}'
    - id: common
      label: Wspólne pliki globalne
      path: '%kernel.root_dir%/../var/uploads/common'
    - id: user
      label: Twoje pliki
      path: '%kernel.root_dir%/../var/uploads/users/{{app.user.username}}'
      condition: '{{app.user is defined ? 1 : 0}}'
      canBeUsedInResources: false

doctrine:
  dbal:
    driver: pdo_pgsql
    host: postgres
    dbname: repeka
    user: postgres
    password: repeka
    server_version: 10.0
    types:
      jsonb: MartinGeorgiev\Doctrine\DBAL\Types\Jsonb
    mapping_types:
      jsonb: jsonb
  orm:
    auto_mapping: false
    mappings:
      RepekaBundle:
        type: yml
        prefix: Repeka\Application\Entity
        dir: "%kernel.root_dir%/../src/Repeka/Application/Resources/config/doctrine/bundle"
        # when the is_bundle is set to false, mapping files can be placed in other than default directory
        # (in this case it is config/doctrine/bundle instead of the default config/doctrine)
        # https://symfony.com/doc/current/reference/configuration/doctrine.html#is-bundle
        is_bundle: false
      RepekaDomain:
        type: yml
        prefix: Repeka\Domain\Entity
        dir: "%kernel.root_dir%/../src/Repeka/Application/Resources/config/doctrine/domain"
        is_bundle: false

doctrine_migrations:
  dir_name: "%kernel.root_dir%/DoctrineMigrations"
  namespace: Repeka\Migrations

framework:
  assets: ~
  csrf_protection: ~
  default_locale: "%locale%"
  form:
    csrf_protection:
      enabled: false
  fragments: ~
  http_method_override: true
  profiler:
    collect: false
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  secret: "%secret%"
  serializer:
    enabled: true
  session:
    handler_id: session.handler.native_file
    save_path: "%kernel.cache_dir%/../../sessions/%kernel.environment%"
  templating:
    engines:
      - twig
  translator:
    fallbacks: ["en"] # must be ['en'] for EN locale to work because of missing translation keys
  trusted_hosts: ~
  validation:
    enable_annotations: true

parameters:
  applicationName: Repeka
  locale: pl
  secret: some_secret
  container.autowiring.strict_mode: true

twig:
  globals:
    applicationName: "%applicationName%"
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
