# https://github.com/elastic/hunspell/blob/master/src/resources/org/elasticsearch/analysis/hunspell/pl/stopwords.txt

repeka:
  elasticsearch:
    stop_words:
      - a
      - aby
      - albo
      - ale
      - ani
      - aż
      - bardzo
      - będą
      - będzie
      - bez
      - bo
      - bowiem
      - by
      - być
      - był
      - była
      - byli
      - było
      - były
      - bym
      - choć
      - chociaż
      - ci
      - cię
      - ciebie
      - co
      - coraz
      - coś
      - często
      - czy
      - czyli
      - d
      - dla
      - dlatego
      - do
      - gdy
      - gdyby
      - gdyż
      - gdzie
      - go
      - i
      - ich
      - im
      - inne
      - iż
      - ja
      - ją
      - jak
      - jakie
      - jako
      - je
      - jednak
      - jego
      - jej
      - jemu
      - jeśli
      - jest
      - jestem
      - jeżeli
      - już
      - kiedy
      - kto
      - która
      - które
      - którego
      - której
      - który
      - których
      - którym
      - którzy
      - labo
      - lecz
      - lub
      - ma
      - mają
      - mam
      - mamy
      - mi
      - miał
      - mną
      - mnie
      - mogą
      - mój
      - moja
      - moje
      - mu
      - my
      - na
      - nad
      - nam
      - nami
      - nas
      - nasz
      - nią
      - nich
      - nie
      - niego
      - niej
      - niemu
      - nim
      - nimi
      - niż
      - no
      - o
      - od
      - on
      - ona
      - one
      - oni
      - ono
      - oraz
      - pan
      - pański
      - po
      - pod
      - ponieważ
      - przed
      - przez
      - przy
      - razie
      - również
      - są
      - sie
      - się
      - siebie
      - sobie
      - swój
      - swoje
      - ta
      - tą
      - tak
      - takich
      - takie
      - także
      - tam
      - tamten
      - te
      - tę
      - tego
      - tej
      - ten
      - też
      - to
      - tobą
      - tobie
      - twój
      - ty
      - tych
      - tylko
      - tym
      - u
      - w
      - wam
      - wami
      - was
      - wasz
      - we
      - więc
      - wiem
      - wy
      - z
      - za
      - zaś
      - zatem
      - ze
      - że
      - żeby
