# I have not added all of them, see the available ones here if you miss something:
# https://github.com/martin-georgiev/postgresql-for-doctrine/tree/develop/src/MartinGeorgiev/Doctrine/ORM/Query/AST/Functions

doctrine:
  orm:
    dql:
      string_functions:
        json_get_field: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonGetField
      numeric_functions:
        jsonb_exists: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\JsonbExists
        contains: MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Contains
