site:
  resource: "@RepekaWebsiteBundle/Controller"
  type: annotation

api:
  resource: "@RepekaBundle/Controller"
  type: annotation
  prefix: /api

ocr:
  resource: "@RepekaOcrPluginBundle/Controller"
  type: annotation
  prefix: /api/plugins/ocr

logout:
  path: /logout
