api:
  resource: "@RepekaBundle/Controller/Api"
  type: annotation
  prefix: /api

site:
  resource: "@RepekaBundle/Controller/Site"
  type: annotation

exposed_endpoints:
  resource: 'Repeka\Application\Service\ResourcesEndpointsExposer:loadRoutes'
  type: service

logout:
  path: /logout
