site:
  resource: "@RepekaBundle/Controller/Site"
  type: annotation

api:
  resource: "@RepekaBundle/Controller/Api"
  type: annotation
  prefix: /api

ocr:
  resource: "@RepekaOcrPluginBundle/Controller"
  type: annotation
  prefix: /api/plugins/ocr

logout:
  path: /logout
