core:
  resource: "@CoreModuleBundle/Controller"
  type: annotation

data:
  resource: "@DataModuleBundle/Controller"
  type: annotation
  prefix: /api

user:
  resource: "@UserModuleBundle/Controller"
  type: annotation

logout:
  path: /logout
