security:
  encoders:
    Repeka\Application\Entity\UserEntity:
      algorithm: bcrypt

  providers:
    db_provider:
      entity:
        class: Repeka\Application\Entity\UserEntity

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true
      simple_form:
        authenticator: Repeka\Application\Authentication\PKAuthenticator
        login_path: login
        check_path: login
        csrf_token_generator: security.csrf.token_manager
      logout:
        path: /logout
        target: /
      remember_me:
        secret: '%secret%'
        lifetime: 604800 # 1 week in seconds
        path: /

  access_control:
    - { path: ^/api, roles: ROLE_OPERATOR }
