services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Repeka\Website\Controller\:
    resource: '../../Controller'
    public: true

  Repeka\Website\Twig\WebpackAssetVersionStrategy:
    arguments:
      - "%use_webpack_dev_server%"
      - "%repeka.webpack_hashes%"
