services:
  repeka.event.authentication_success_listener:
    class: Repeka\UserModule\Bundle\EventListener\JwtTokenCookieSetter
    autowire: true
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
