version: '3'

services:
  repeka:
    container_name: ${COMPOSE_PROJECT_NAME}
    networks: [default]
    restart: unless-stopped
    build:
      context: ./repeka
      args:
        WWW_DATA_UID: ${UID}
    volumes:
      - ../:/var/www/html:z
      - ../var/ssl:/etc/apache2/ssl:z
    links:
      - repeka-postgres:postgres

  repeka-postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:10.0
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
