version: '2'

services:
  repeka:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: ./repeka
      args:
        WWW_DATA_UID: ${UID}
    volumes:
      - ../:/var/www/html:z
      - ../var/ssl:/etc/apache2/ssl:z
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    links:
      - repeka-elasticsearch:elasticsearch
      - repeka-postgres:postgres

  repeka-elasticsearch:
    container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
    build:
      context: ./elasticsearch

  repeka-postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:10.0
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
