version: '2'

services:
  repeka:
    container_name: ${REPEKA_CONTAINER_NAME}
    build: ./repeka
    volumes:
      - ${REPEKA_VOLUME_SOURCES}:/var/www/html:z
    ports:
      - "${REPEKA_PORT_HTTP}:80"
      - "${REPEKA_PORT_HTTPS}:443"
    links:
      - repeka-elasticsearch:elasticsearch
      - repeka-postgres:postgres
      - repeka-metrics:metrics

  repeka-elasticsearch:
    container_name: ${REPEKA_CONTAINER_NAME_ELASTICSEARCH}
    image: elasticsearch:2.4.2
    command: -Des.node.name="repeka-elasticsearch"
    volumes:
      - ${REPEKA_VOLUME_ELASTICSEARCH}:/usr/share/elasticsearch/data:z

  repeka-postgres:
    container_name: ${REPEKA_CONTAINER_NAME_POSTGRES}
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: ${REPEKA_DATABASE_PASSWORD}
    volumes:
      - ${REPEKA_VOLUME_POSTGRES}:/var/lib/postgresql/data:z

  repeka-metrics:
    container_name: ${REPEKA_CONTAINER_NAME_METRICS}
    build: ./repeka-metrics
    volumes:
      - ${REPEKA_VOLUME_METRICS}/data/whisper:/opt/graphite/storage/whisper:z
      - ${REPEKA_VOLUME_METRICS}/data/elasticsearch:/var/lib/elasticsearch:z
      - ${REPEKA_VOLUME_METRICS}/data/grafana:/opt/grafana/data:z
      - ${REPEKA_VOLUME_METRICS}/log/graphite:/opt/graphite/storage/log:z
      - ${REPEKA_VOLUME_METRICS}/log/elasticsearch:/var/log/elasticsearch:z

