services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Repeka\DeveloperBundle\DataFixtures\Cmi\:
    resource: '../../DataFixtures/Cmi'
    tags: [{name: doctrine.fixture.orm, group: cmi}]

  Repeka\DeveloperBundle\DataFixtures\Redo\:
    resource: '../../DataFixtures/Redo'
    tags: [{name: doctrine.fixture.orm, group: redo}]

  Repeka\DeveloperBundle\Command\:
    resource: '../../Command'
