services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Repeka\DeveloperBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: [doctrine.fixture.orm]

  Repeka\DeveloperBundle\Command\:
    resource: '../../Command'
