parameters:
  secret: soo_secret
  applicationName: repeka
doctrine:
  dbal:
    host: 127.0.0.1
    user: postgres
    password: postgres
repeka:
  resource_classes:
    - name: books
      icon: publish-4
      admins:
        - Username: admin
      operators:
        - Username: budynek
        - Username: tester
        - Username: skaner
    - name: dictionaries
      icon: dictionary
      admins:
        - Username: admin
        - Username: skaner
    - name: users
      icon: user
      admins:
        - Username: admin
    - name: cms
      icon: html
      admins:
        - Username: admin
    - name: remarks
      icon: mail
      admins:
        - Username: admin
  metadata_groups:
    - id: basic
      label:
        EN: Basic metadata
        PL: Podstawowe metadane
    - id: cms
      label:
        EN: Metadata used in CMS
        PL: Metadane używane w CMS
  elasticsearch:
    host: localhost
  templating:
    templates_resource_class: cms
    theme: redo
  audit:
    - id: no_filters
      url:
      label:
        EN: No filters
        PL: Brak filtrów
    - id: example_users_year_2019
      url: commandNames=user_authenticate&dateFrom=2019-01-01
      label:
        EN: Users that logon from year 2019
        PL: Użytkownicy logujący się od roku 2019
    - id: created_year_2018
      url: dateFrom=2018-01-01&dateTo=2018-12-31&resourceContents={"tytuł":"Python"}&users=1038%2C1040
      label:
        EN: Books titled 'Python' in year 2018
        PL: Książki o tytule 'Python' w roku 2018
    - id: january_2019
      url: commandNames=resource_create&dateFrom=2019-01-01&dateTo=2019-01-31&resourceKinds=-1
      label:
        EN: Users created in January 2019
        PL: Użytkownicy stworzeni w styczniu 2019
    - id: all_2019
      url: customColumns=["{{r|mTytul}}"]&resultsPerPage=500
      label:
        EN: All audit entries with pagination and title
        PL: Wszystkie wpisy audytu z paginacją i tytułem
  expose_endpoints:
    /about:
      resourceId: 23
      metadata: wyrenderowana_tresc_strony
    /resources/{resourceId}:
      template: redo/resource-details/resource-details.twig
      endpointUsageTrackingKey: resourceDetails
    /resources/{resourceId}/bibtex:
      template: redo/citation-formats/bibtex.twig
      endpointUsageTrackingKey: bibtex
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/endnote:
      template: redo/citation-formats/endnote.twig
      endpointUsageTrackingKey: endnote
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/iso-690:
      template: redo/citation-formats/iso-690.twig
      endpointUsageTrackingKey: iso-690
    /resources/{resourceId}/rss:
      template: redo/rss/collection.rss.twig
      endpointUsageTrackingKey: rss
      headers:
        Content-Type: 'application/rss+xml'
m6_statsd:
  servers:
    default:
      address: 'udp://localhost'

redo:
  fts:
    searchable_metadata_ids: [-5, tytul, opis, url, urlLabel]
    filterable_metadata_ids: [tytul, opis, parent_path, wydzial, skanista, nadzorujacy]
    searchable_resource_classes: [books]
    facets: [kindId, skanista]
  captcha:
    public_key: 6LepBqQUAAAAAL6-5hTmjGGawPjeR7UEx8YUcaSg
    private_key: 6LepBqQUAAAAADU-EQhUQ6EIj1q59f7Q-1cjJSNq

# Downlad wkhtmltopdf archive for your OS from https://github.com/wkhtmltopdf/wkhtmltopdf/releases/latest
# and extract it to var directory in the project root; ensure the path below is ok
repeka_pdf_generator_plugin:
  wkHtmlToPdfPath: '%kernel.root_dir%/../var/wkhtmltox/bin/wkhtmltopdf.exe'
