parameters:
  secret: soo_secret
  applicationName: repeka
doctrine:
  dbal:
    host: 127.0.0.1
    user: postgres
    password: postgres
repeka:
  application_url: http://repeka.local
  resource_classes:
    - name: books
      icon: publish-4
      admins:
        - Username: admin
      operators:
        - Username: budynek
        - Username: tester
        - Username: skaner
    - name: dictionaries
      icon: dictionary
      admins:
        - Username: admin
    - name: users
      icon: user
      admins:
        - Username: admin
    - name: cms
      icon: html
      admins:
        - Username: admin
  metadata_groups:
    - id: basic
      label:
        EN: Basic metadata
        PL: Podstawowe metadane
    - id: cms
      label:
        EN: Metadata used in CMS
        PL: Metadane używane w CMS
  elasticsearch:
    host: localhost
  templating:
    templates_resource_class: cms
    templates:
      login_form: redo/login-form.twig
      error_page: redo/error-page.twig
  expose_endpoints:
    /about:
      resourceId: 18
      metadata: wyrenderowana_tresc_strony
    /resources/{resourceId}:
      template: redo/resource-details/resource-details.twig
    /resources/{resourceId}/bibtex:
      template: redo/citation-formats/bibtex.twig
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/endnote:
      template: redo/citation-formats/endnote.twig
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/iso-690:
      template: redo/citation-formats/iso-690.twig
    /resources/{resourceId}/rss:
      template: redo/rss/collection.rss.twig
      headers:
        Content-Type: 'application/rss+xml'
    /deposit/{phase}:
      template: redo/deposit.twig
      deposit:
        relationship_resource_kind_ids: [1, 2, -1, 7]
m6_statsd:
  servers:
    default:
      address: 'udp://localhost'

redo:
  fts:
    searchable_metadata_ids: [-5, tytul, opis, url, urlLabel]
    filterable_metadata_ids: [tytul, opis, parent, wydzial, skanista, nadzorujacy]
    searchable_resource_classes: [books]
    facets: [kindId, skanista]
