parameters:
  applicationName: REDO
  secret: soo_secret
doctrine:
  dbal:
    password: THIS_IS_THE_DB_PASSWORD_TO_BE_REPLACED_DURING_BUILD
repeka:
  resource_classes:
    - name: books
      icon: publish-4
      admins:
        - Username: admin
        - Group member: 82
        - Group member: 357
      operators:
        - Group member: 358
        - Username: operator.*
    - name: dictionaries
      icon: dictionary
      admins:
        - Username: admin
        - Group member: 82
      operators:
        - Username: operator.*
    - name: users
      icon: user
      admins:
        - Username: admin
      operators:
        - Username: admin
    - name: cms
      icon: html
      admins:
        - Username: admin
  metadata_groups:
    - id: basic
      label:
        EN: Basic metadata
        PL: Podstawowe metadane
    - id: cms
      label:
        EN: Metadata used in CMS
        PL: Metadane używane w CMS
  templating:
    templates_resource_class: cms
    templates:
      login_form: redo/login-form.twig
      error_page: redo/error-page.twig
  expose_endpoints:
    /about:
      metadata: imported_file_template
      resourceId: 1978
    /resources/{resourceId}:
      template: redo/resource-details/resource-details.twig
    /static/{resourceId}:
      metadata: imported_file_template
    /resources/{resourceId}/bibtex:
      template: bibtex/bibtex.twig
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/rss:
      template: redo/rss/collection.rss.twig
      headers:
        Content-Type: 'application/rss+xml'
    /deposit/{phase}:
      template: redo/deposit.twig
      deposit:
        relationship_resource_kind_ids: [1, 2, -1, 7, 48]

redo:
  fts:
    searchable_metadata_ids: [-5, tytul, autor, opis, wydzial, barkod, zasob_plik]
    filterable_metadata_ids: [parent, tytul, autor, opis, wydzial, barkod]
    searchable_resource_classes: [books]
    facets: [kindId]
