doctrine:
  dbal:
    password: THIS_IS_THE_DB_PASSWORD_TO_BE_REPLACED_DURING_BUILD
repeka:
  resource_classes:
    - name: books
      icon: publish-4
      admins:
        - Username: admin
      operators:
        - Username: budynek
        - Username: tester
        - Username: skaner
    - name: dictionaries
      icon: dictionary
      admins:
        - Username: admin
        - Username: skaner
    - name: users
      icon: user
      admins:
        - Username: admin
    - name: grants
      icon: user
      admins:
        - Username: admin
    - name: remarks
      icon: mail
      admins:
        - Username: admin
    - name: features
      icon: publish
      admins:
        - Username: admin
  metadata_groups:
    - id: basic
      label:
        EN: Basic metadata
        PL: Podstawowe metadane
  templating:
    theme: redo
  upload_dirs:
    - id: grant_files
      label: Pliki wniosku
      condition: '{{resource|mnr_formularza|length == 1 ? 1 : 0}}'
      path: '%kernel.root_dir%/../var/grant_files/{{resource|mnr_formularza}}'
