parameters:
  secret: soo_secret
  applicationName: repeka
doctrine:
  dbal:
    host: 127.0.0.1
    user: postgres
    password: postgres
repeka:
  resource_classes:
    - name: books
      icon: publish-4
      admins:
        - Username: admin
      operators:
        - Username: budynek
        - Username: tester
        - Username: skaner
    - name: dictionaries
      icon: dictionary
      admins:
        - Username: admin
        - Username: skaner
    - name: users
      icon: user
      admins:
        - Username: admin
    - name: cms
      icon: html
      admins:
        - Username: admin
  metadata_groups:
    - id: basic
      label:
        EN: Basic metadata
        PL: Podstawowe metadane
    - id: cms
      label:
        EN: Metadata used in CMS
        PL: Metadane używane w CMS
  elasticsearch:
    host: localhost
  templating:
    templates_resource_class: cms
    theme: redo
  audit:
    - id: no_filters
      url:
      label:
        EN: No filters
        PL: Brak filtrów
    - id: example_users_year_2019
      url: commandNames=user_authenticate&dateFrom=2019-01-01
      label:
        EN: Users that logon from year 2019
        PL: Użytkownicy logujący się od roku 2019
    - id: created_year_2018
      url: dateFrom=2018-01-01&dateTo=2018-12-31&resourceContents={"tytuł":"Python"}&users=1038%2C1040
      label:
        EN: Books titled 'Python' in year 2018
        PL: Książki o tytule 'Python' w roku 2018
    - id: january_2019
      url: commandNames=resource_create&dateFrom=2019-01-01&dateTo=2019-01-31&resourceKinds=-1
      label:
        EN: Users created in January 2019
        PL: Użytkownicy stworzeni w styczniu 2019
    - id: all_2019
      url: customColumns=["{{r|mTytul}}"]&resultsPerPage=500
      label:
        EN: All audit entries with pagination and title
        PL: Wszystkie wpisy audytu z paginacją i tytułem
  statistics:
    - usageKey: home
      label:
        EN: Home page
        PL: Strona główna
    - usageKey: ips
      label:
        EN: The most popular IP addresses
        PL: Najpopularniejsze adresy IP
    - usageKey: sessions
      label:
        EN: Number of sessions
        PL: Liczba sesji
    - usageKey: resourceDetails
      label:
        EN: Resource details
        PL: Szczegóły zasobów
    - usageKey: bibtex
      label:
        EN: Bibtex details
        PL: Wyświetlenia w formacie bibtex
    - usageKey: endnote
      label:
        EN: Endnote details
        PL: Wyświetlenia w formacie endnote
    - usageKey: iso-690
      label:
        EN: ISO-690 details
        PL: Wyświetlenia w formacie ISO-690
    - usageKey: rss
      label:
        EN: RSS details
        PL: Wyświetlenia w formacie RSS
    - usageKey: deposit
      label:
        EN: Deposited resources by users
        PL: Zdeponowane zasoby przez użytkowników
  expose_endpoints:
    /about:
      resourceId: 19
      metadata: wyrenderowana_tresc_strony
    /resources/{resourceId}:
      template: redo/resource-details/resource-details.twig
      endpointUsageTrackingKey: resourceDetails
    /resources/{resourceId}/bibtex:
      template: redo/citation-formats/bibtex.twig
      endpointUsageTrackingKey: bibtex
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/endnote:
      template: redo/citation-formats/endnote.twig
      endpointUsageTrackingKey: endnote
      headers:
        Content-Type: 'text/plain'
    /resources/{resourceId}/iso-690:
      template: redo/citation-formats/iso-690.twig
      endpointUsageTrackingKey: iso-690
    /resources/{resourceId}/rss:
      template: redo/rss/collection.rss.twig
      endpointUsageTrackingKey: rss
      headers:
        Content-Type: 'application/rss+xml'
    /resources/{resourceId}/browse:
      template: redo/resource-details/image-reader.twig
m6_statsd:
  servers:
    default:
      address: 'udp://localhost'

redo:
  fts:
    searchable_metadata_ids: [-5, tytul, opis, url, urlLabel]
    filterable_metadata_ids: [tytul, opis, parent_path, wydzial, skanista, nadzorujacy]
    searchable_resource_classes: [books]
    facets: [kindId, skanista]
