services:
  Repeka\Domain\Cqrs\CommandBus: '@Repeka\Application\Cqrs\RepekaCommandBus'
  Repeka\Domain\Factory\ResourceWorkflowDriverFactory: '@Repeka\Application\Factory\SymfonyResourceWorkflowDriverFactory'
  Repeka\Domain\Factory\UserFactory: '@Repeka\Application\Factory\UserEntityFactory'
  Repeka\Domain\Repository\AuditEntryRepository: '@Repeka\Application\Repository\AuditEntryDoctrineRepository'
  Repeka\Domain\Repository\LanguageRepository: '@Repeka\Application\Repository\LanguageDoctrineRepository'
  Repeka\Domain\Repository\MetadataRepository: '@Repeka\Application\Repository\MetadataDoctrineRepository'
  Repeka\Domain\Repository\RepositoryProvider: '@Repeka\Application\Repository\ContainerAwareRepositoryProvider'
  Repeka\Domain\Repository\ResourceKindRepository: '@Repeka\Application\Repository\ResourceKindDoctrineRepository'
  Repeka\Domain\Repository\ResourceRepository: '@Repeka\Application\Repository\ResourceDoctrineRepository'
  Repeka\Domain\Repository\ResourceKindDoctrineRepository: '@Repeka\Application\Repository\ResourceKindDoctrineRepository'
  Repeka\Domain\Repository\ResourceWorkflowRepository: '@Repeka\Application\Repository\ResourceWorkflowDoctrineRepository'
  Repeka\Domain\Repository\UserRepository: '@Repeka\Application\Repository\UserDoctrineRepository'
  Repeka\Domain\Repository\UserRoleRepository: '@Repeka\Application\Repository\UserRoleDoctrineRepository'
  Repeka\Domain\Service\RegexNormalizer: '@Repeka\Application\Service\PhpRegexNormalizer'
  Repeka\Domain\Service\ResourceDisplayStrategyEvaluator: '@Repeka\Application\Service\LightnCandyHandlebarsResourceDisplayStrategyEvaluator'
  Repeka\Domain\Upload\ResourceFileHelper: '@Repeka\Application\Upload\BasicResourceFileHelper'
  Repeka\Domain\Validation\MetadataConstraintManager: '@Repeka\Application\Validation\ContainerAwareMetadataConstraintManager'
  Repeka\Domain\Workflow\ResourceWorkflowPlugins: '@Repeka\Application\Workflow\RepekaResourceWorkflowPlugins'

  Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'
  M6Web\Component\Statsd\Client: '@m6_statsd'
  Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface: '@Repeka\Domain\Repository\UserRepository'
  Symfony\Component\Security\Core\Authentication\AuthenticationManagerInterface: '@security.authentication.manager'
