services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Repeka\Domain\Metadata\MetadataImport\Transform\ImportTransform:
      tags: [repeka.import_transform]
    Repeka\Domain\Metadata\SearchValueAdjuster\SearchValueAdjuster:
      tags: [repeka.search_value_adjuster]
    Repeka\Application\Elasticsearch\Model\ElasticSearchQueryCreator\ElasticSearchQueryCreator:
      tags: [repeka.elastic_search_query_creator]

  Repeka\Application\Elasticsearch\:
    resource: '../../Elasticsearch'

  Repeka\Application\Authentication\:
    resource: '../../Authentication'

  Repeka\Application\Command\:
    resource: '../../Command'

  Repeka\Application\Controller\:
    resource: '../../Controller'
    public: true

  Repeka\Application\Cqrs\Middleware\:
    resource: '../../Cqrs/Middleware'

  Repeka\Application\Factory\:
    resource: '../../Factory'

  Repeka\Application\Security\:
    resource: '../../Security'

  Repeka\Application\Serialization\:
    resource: '../../Serialization'

  Repeka\Application\Service\:
    resource: '../../Service'

  Repeka\Application\Twig\:
    resource: '../../Twig'

  Repeka\Domain\:
    resource: '../../../Domain'
    exclude: '../../../Domain/Entity'

  Repeka\Domain\UseCase\:
    public: true
    resource: '../../../Domain/UseCase'
    exclude: '../../../Domain/UseCase/**/*{Command,Query}.php'
