services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Repeka\Application\ParamConverter\MetadataValueProcessor\MetadataValueProcessorStrategy:
      tags: [repeka.metadata_value_processor]
    Repeka\Domain\MetadataImport\Transform\ImportTransform:
      tags: [repeka.import_transform]
    Repeka\Domain\Validation\MetadataConstraints\AbstractMetadataConstraint:
      tags: [repeka.metadata_constraint]

  Repeka\Application\Authentication\:
    resource: '../../Authentication'

  Repeka\Application\Command\:
    resource: '../../Command'

  Repeka\Application\Controller\:
    resource: '../../Controller'
    public: true

  Repeka\Application\Cqrs\Middleware\:
    resource: '../../Cqrs/Middleware'

  Repeka\Application\Factory\:
    resource: '../../Factory'

  Repeka\Application\ParamConverter\MetadataValueProcessor\:
    resource: '../../ParamConverter/MetadataValueProcessor'

  Repeka\Application\Serialization\:
    resource: '../../Serialization'

  Repeka\Application\Service\:
    resource: '../../Service'

  Repeka\Application\Twig\:
    resource: '../../Twig'

  Repeka\Application\MetadataImport\:
    resource: '../../MetadataImport'

  Repeka\Domain\:
    resource: '../../../Domain'
    exclude: '../../../Domain/Entity'

  Repeka\Domain\UseCase\:
    public: true
    resource: '../../../Domain/UseCase'
    exclude: '../../../Domain/UseCase/**/*{Command,Query}.php'
