imports:
  - {resource: autodiscovery.yml}
  - {resource: aliases.yml}
  - {resource: repositories.yml}

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Repeka\Application\Authentication\LocalDatabaseAuthenticator: ~

  Repeka\Application\Authentication\CompositeAuthenticator:
    $authenticators: !tagged repeka.token_authenticator

  Repeka\Application\Command\Cyclic\DispatchCyclicTasksCommand:
    - !tagged repeka.cyclic_command

  Repeka\Domain\Metadata\MetadataImport\Transform\ImportTransformComposite:
    - !tagged repeka.import_transform

  Repeka\Application\Cqrs\Middleware\DispatchCommandEventsMiddleware:
    - !tagged repeka.command_events_listener

  Repeka\Application\Command\Initialization\InitializeApplicationCommand:
    - !tagged repeka.initialization_command

  Repeka\Application\Command\Initialization\InitializeSystemLanguagesCommand:
    tags: [{name: repeka.initialization_command, priority: 600}]
  Repeka\Application\Command\Initialization\InitializeSystemMetadataCommand:
    tags: [{name: repeka.initialization_command, priority: 500}]
  Repeka\Application\Command\Initialization\InitializeSystemResourceKindsCommand:
    tags: [{name: repeka.initialization_command, priority: 400}]
  Repeka\Application\Command\Initialization\InitializeSystemResourcesCommand:
    tags: [{name: repeka.initialization_command, priority: 300}]

  Repeka\Application\Cqrs\RepekaCommandBus:
    -
      - '@Repeka\Application\Cqrs\Middleware\MetricsCommandBusMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\AdjustCommandMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\AuditCommandMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\FirewallMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\ValidateCommandMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\WrapCommandWithTransactionMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\DispatchCommandEventsMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\CallCommandHandlerMiddleware'

  Repeka\Application\Elasticsearch\ESClient:
    - '%elasticsearch.host%'
    - '%elasticsearch.port%'
    - '%elasticsearch.proxy%'
  Repeka\Application\Elasticsearch\ESIndexManager:
    arguments:
      $indexName: '%elasticsearch.index_name%'
      $stopWords: '%elasticsearch.stop_words%'
  Repeka\Application\Elasticsearch\PageNumberFinder: ~
  Repeka\Application\Elasticsearch\Mapping\ESMapping: ~
  Repeka\Application\Elasticsearch\Model\ESContentsAdjuster: ~
  Repeka\Application\Elasticsearch\Model\ElasticSearchContext:
    arguments:
      $indexName: '%elasticsearch.index_name%'
      $stopWords: '%elasticsearch.stop_words%'
  Repeka\Application\Elasticsearch\Model\ElasticSearchQueryPhraseAdjuster:
    properties:
      stopWords: '%elasticsearch.stop_words%'

  Repeka\Application\Elasticsearch\Model\ElasticSearch:
    shared: false

  Repeka\Application\Entity\EntityIdGeneratorHelper: ~

  Repeka\Application\EventListener\AdminPanelMetricsRequestListener:
    arguments:
      $namesWhitelist: '%admin_panel_metrics%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  Repeka\Application\EventListener\AuthenticationAuditListener:
    tags:
      - { event: security.interactive_login, name: kernel.event_listener }
      - { event: security.authentication.failure, name: kernel.event_listener }
  Repeka\Application\EventListener\CsrfRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 0 }
  Repeka\Application\EventListener\GlobalExceptionListener:
    arguments:
      $isDebug: '%kernel.debug%'
      $theme: '%repeka.theme%'
      $exceptionLogger: '@monolog.logger.exception_listener'
      $userErrorLogger: '@monolog.logger.user_error'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException, priority: 1000 }
  Repeka\Application\EventListener\UserLocaleListener:
    arguments:
      $fallbackLocales: '%repeka.fallback_ui_languages%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1020 }
      # must be called before LocaleListener, which has priority of 16, by assigning higher priority
      # must be called before GlobalExceptionListener which has priority of 1000, by assigning higher priority, or error uses default locale

  Repeka\Application\EventListener\Doctrine\ResourceKindMetadataListConverterListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: postLoad }

  Repeka\Application\EventListener\Doctrine\ResourceWorkflowDriverInjector:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  Repeka\Application\Security\Voters\ResourceClassAdminVoter:
    tags:
      - { name: security.voter, priority: 100 }

  Repeka\Application\Service\FileSystemResourceFileStorage:
    $uploadDirs: '%repeka.upload_dirs%'

  Repeka\Application\Service\PluginsRoutesLoader:
    public: true
    arguments:
      $theme: '%repeka.theme%'
      $routeLoader: '@routing.loader.annotation'
  Repeka\Application\Service\ResourcesEndpointsExposer:
    public: true
    arguments:
      $exposedEndpoints: '%repeka.exposed_endpoints%'

  Repeka\Application\Twig\ResourcesTwigLoader:
    arguments:
      $templatesResourceClass: '%repeka.templates_resource_class%'
    tags:
      - {name: twig.loader, priority: 100}

  Repeka\Application\Resources\FrontendLocaleProvider:
    $defaultUiLanguage: '%repeka.default_ui_language%'

  Repeka\Domain\Validation\MetadataConstraintManager:
    - !tagged repeka.metadata_constraint

  Repeka\Domain\Validation\Rules\ResourceClassExistsRule:
    $resourceClasses: '%repeka.resource_classes%'

  Repeka\Domain\Validation\Strippers\UnknownMetadataGroupStripper:
    $metadataGroups: '%repeka.metadata_groups%'

  Repeka\Domain\Workflow\ResourceWorkflowPlugins:
    - !tagged repeka.workflow_plugin

  Repeka\Domain\Workflow\Loader\ResourcesSchemaLoader: ~

  Monolog\Formatter\LineFormatter: [~, ~, true]
  Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener:
    tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }]

  Repeka\Domain\UseCase\User\UserGrantRolesCommandHandler:
    public: true
    arguments:
      $resourceClassesConfig: '%repeka.resource_classes_config%'

  Repeka\Domain\Metadata\MetadataValueAdjuster\MetadataValueAdjusterComposite:
    - !tagged repeka.metadata_value_adjuster

  Repeka\Domain\Metadata\SearchValueAdjuster\SearchValueAdjusterComposite:
    - !tagged repeka.search_value_adjuster

  Repeka\Application\Elasticsearch\Model\ElasticSearchQueryCreator\ElasticSearchQueryCreatorComposite:
    - !tagged repeka.elastic_search_query_creator
