imports:
  - {resource: autodiscovery.yml}
  - {resource: aliases.yml}
  - {resource: repositories.yml}

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Repeka\Application\Authentication\PKSoapService:
    - '%pk_auth.wsdl%'
    - '%pk_auth.options%'
  Repeka\Application\Authentication\TokenAuthenticator\LocalDatabaseAuthenticator:
    $localAccountsEnabled: '%pk_auth.local_accounts_enabled%'
  Repeka\Application\Authentication\PKUserDataUpdater: ~
  Repeka\Application\Authentication\UserDataMapping:
    $mappingConfigPath: '%user_data_mapping%'

  Repeka\Application\MetadataImport\KohaXmlResourceDownloader:
    - '%xml_import.koha%'

  Repeka\Domain\MetadataImport\Transform\ImportTransformComposite:
    - !tagged repeka.import_transform

  Repeka\Application\Cqrs\Middleware\DispatchCommandEventsMiddleware:
    - !tagged repeka.command_events_listener

  Repeka\Application\Cqrs\RepekaCommandBus:
    -
      - '@Repeka\Application\Cqrs\Middleware\MetricsCommandBusMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\AdjustCommandMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\AuditCommandMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\FirewallMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\ValidateCommandMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\DispatchCommandEventsMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\WrapCommandWithTransactionMiddleware'
      - '@Repeka\Application\Cqrs\Middleware\CallCommandHandlerMiddleware'

  Repeka\Application\Elasticsearch\ESClient:
    - '%elasticsearch.host%'
    - '%elasticsearch.port%'
    - '%elasticsearch.proxy%'
  Repeka\Application\Elasticsearch\ESIndexManager:
    $indexName: '%elasticsearch.index_name%'
  Repeka\Application\Elasticsearch\Mapping\ESMappingFactory:
    $nestingDepth: '%repeka.max_nesting_depth%'
    $analyzerNames: '%elasticsearch.analyzers%'
    $metadataClasses:
      - 'Repeka\Application\Elasticsearch\Model\IntIndexedMetadata'
      - 'Repeka\Application\Elasticsearch\Model\FloatIndexedMetadata'
      - 'Repeka\Application\Elasticsearch\Model\DateTimeIndexedMetadata'
      - 'Repeka\Application\Elasticsearch\Model\RawStringIndexedMetadata'
      - 'Repeka\Application\Elasticsearch\Model\TokenizedStringIndexedMetadata'
      - 'Repeka\Application\Elasticsearch\Model\AnalyzedStringIndexedMetadata'
  Repeka\Application\Elasticsearch\Model\ESResource:
    shared: false
    arguments:
      $indexName: '%elasticsearch.index_name%'

  Repeka\Application\Entity\EntityIdGeneratorHelper: ~

  Repeka\Application\EventListener\AdminPanelMetricsRequestListener:
    arguments:
      $namesWhitelist: '%admin_panel_metrics%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  Repeka\Application\EventListener\AuthenticationAuditListener:
    tags:
      - { event: security.interactive_login, name: kernel.event_listener }
      - { event: security.authentication.failure, name: kernel.event_listener }
  Repeka\Application\EventListener\CsrfRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 0 }
  Repeka\Application\EventListener\GlobalExceptionListener:
    arguments:
      $isDebug: '%kernel.debug%'
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException, priority: 1000 }
      - { name: monolog.logger, channel: exception_listener }

  Repeka\Application\EventListener\Doctrine\ResourceKindMetadataListConverterListener:
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
      - { name: doctrine.event_listener, event: postLoad }

  Repeka\Application\EventListener\Doctrine\ResourceWorkflowDriverInjector:
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  Repeka\Application\Service\ResourcesEndpointsExposer:
    public: true
    arguments:
      $exposedEndpoints: '%repeka.exposed_endpoints%'

  Repeka\Application\Twig\ResourcesTwigLoader:
    arguments:
      $templatesResourceClass: '%repeka.templates_resource_class%'
    tags:
      - {name: twig.loader, priority: 100}

  Repeka\Application\Twig\WebpackAssetVersionStrategy:
    arguments:
      - "%use_webpack_dev_server%"
      - "%repeka.webpack_hashes%"

  Repeka\Application\ParamConverter\ResourceContentsParamConverter:
    tags: [{ name: request.param_converter, converter: Repeka\Application\ParamConverter\ResourceContentsParamConverter }]
  Repeka\Application\ParamConverter\MetadataValueProcessor\MetadataValueProcessor:
    public: true

  Repeka\Application\Resources\FrontendLocaleProvider:
    $defaultUiLanguage: '%repeka.default_ui_language%'

  Repeka\Application\Upload\FilesystemDriver: ~
  Repeka\Application\Upload\BasicResourceFileHelper: ~
  Repeka\Application\Upload\ResourceFilePathGenerator:
    - '%repeka.upload.path%'
    - '%repeka.upload.temp_folder%'

  Repeka\Application\Validation\ContainerAwareMetadataConstraintManager:
    - !tagged repeka.metadata_constraint

  Repeka\Domain\Validation\Rules\ResourceClassExistsRule:
    $resourceClasses: '%repeka.resource_classes%'

  Repeka\Domain\Workflow\ResourceWorkflowPlugins:
    - !tagged repeka.workflow_plugin

  Monolog\Formatter\LineFormatter: [~, ~, true]
  Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener:
    tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }]

  Repeka\Domain\UseCase\User\UserGrantRolesCommandHandler:
    public: true
    arguments:
      $resourceClassesConfig: '%repeka.resource_classes_config%'
