Repeka\Application\Entity\UserEntity:
  exclusion_policy: ALL
  read_only: true
  properties:
    id: ~
    username: {access_type: public_method}
    email: {access_type: public_method}
    firstname: {access_type: public_method}
    lastname: {access_type: public_method}
    staticPermissions: {access_type: public_method}
