Repeka\Domain\Entity\EndpointUsageLogEntry:
  type: entity
  table: endpoint_usage_log
  repositoryClass: Repeka\Application\Repository\EndpointUsageLogDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    resource:
      targetEntity: Repeka\Domain\Entity\ResourceEntity
      joinColumn:
        name: resource_id
        referencedColumnName: id
        nullable: true
  fields:
    url:
      type: string
    clientIp:
      type: string
      column: client_ip
    usageDateTime:
      type: datetimetz_immutable
      options: {default: CURRENT_TIMESTAMP}
      column: usage_date_time
    usageKey:
      type: string
      column: usage_key
