Repeka\Domain\Entity\EventLogEntry:
  type: entity
  table: event_log
  repositoryClass: Repeka\Application\Repository\EventLogDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    resource:
      targetEntity: Repeka\Domain\Entity\ResourceEntity
      joinColumn:
        name: resource_id
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
  fields:
    url:
      type: string
    clientIp:
      type: string
      column: client_ip
    eventDateTime:
      type: datetimetz_immutable
      options: {default: CURRENT_TIMESTAMP}
      column: event_date_time
    eventName:
      type: string
      column: event_name
