Repeka\Domain\Entity\Language:
  type: entity
  table: language
  repositoryClass: Repeka\Application\Repository\LanguageDoctrineRepository
  id:
    code:
      type: string
      length: 5
      unique: true
  fields:
    flag:
      type: string
      length: 10
    name:
      type: string
      length: 255
