Repeka\Domain\Entity\Metadata:
  type: entity
  table: metadata
  repositoryClass: Repeka\Application\Repository\MetadataDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    resourceKind:
      targetEntity: Repeka\Domain\Entity\ResourceKind
      inversedBy: metadataList
      joinColumn:
        name: resource_kind_id
        referencedColumnName: id
    baseMetadata:
      targetEntity: Repeka\Domain\Entity\Metadata
      fetch: EAGER
      joinColumn:
        name: base_id
        referencedColumnName: id
  fields:
    control:
      type: string
      length: 25
      nullable: true
    name:
      type: string
      length: 255
      nullable: true
    label:
      type: json_document
      options: {jsonb: true}
    description:
      type: json_document
      options: {jsonb: true}
    placeholder:
      type: json_document
      options: {jsonb: true}
    ordinalNumber:
      type: integer
      nullable: false
      column: ordinal_number
      options: {default: 0}
