Repeka\Domain\Entity\Metadata:
  type: entity
  table: metadata
  repositoryClass: Repeka\Application\Repository\MetadataDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    baseMetadata:
      targetEntity: Repeka\Domain\Entity\Metadata
      fetch: EAGER
      joinColumn:
        name: base_id
        referencedColumnName: id
    parentMetadata:
      targetEntity: Repeka\Domain\Entity\Metadata
      fetch: EAGER
      joinColumn:
        name: parent_id
        referencedColumnName: id
  fields:
    control:
      type: string
      length: 25
    name:
      type: string
      length: 255
      nullable: true
    label:
      type: jsonb
    description:
      type: jsonb
      options: {default: '{}'}
    placeholder:
      type: jsonb
      options: {default: '{}'}
    ordinalNumber:
      type: integer
      nullable: false
      column: ordinal_number
      options: {default: 0}
    constraints:
      type: jsonb
    shownInBrief:
      type: boolean
      column: shown_in_brief
    resourceClass:
      type: string
      length: 64
      column: resource_class
