Repeka\Domain\Entity\ResourceKind:
  type: entity
  table: resource_kind
  repositoryClass: Repeka\Application\Repository\ResourceKindDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  oneToMany:
    metadataList:
      orderBy: {ordinalNumber: 'ASC'}
      targetEntity: Repeka\Domain\Entity\Metadata
      mappedBy: resourceKind
      orphanRemoval: true
      cascade: ["persist", "merge", "remove"]
  manyToOne:
    workflow:
      targetEntity: Repeka\Domain\Entity\ResourceWorkflow
      joinColumn:
        name: workflow_id
        referencedColumnName: id
  fields:
    label:
      type: json_document
      options: {jsonb: true}
