Repeka\Domain\Entity\ResourceWorkflow:
  type: entity
  table: workflow
  repositoryClass: Repeka\Application\Repository\ResourceWorkflowDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: json_document
      options: {jsonb: true}
    places:
      type: json
      options: {default: '[]', jsonb: true}
    transitions:
      type: json
      options: {default: '[]', jsonb: true}
    diagram:
      type: text
      nullable: true
    thumbnail:
      type: text
      nullable: true
