Repeka\Domain\Entity\ResourceKind:
  type: entity
  table: resource_kind
  repositoryClass: Repeka\Application\Repository\ResourceKindDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    workflow:
      targetEntity: Repeka\Domain\Entity\ResourceWorkflow
      joinColumn:
        name: workflow_id
        referencedColumnName: id
  fields:
    name:
      type: string
      length: 255
      nullable: false
    label:
      type: jsonb
    resourceClass:
      type: string
      length: 64
      nullable: false
      column: resource_class
    allowedToClone:
      type: boolean
      column: allowed_to_clone
      options: {default: false}
    metadataOverrides:
      type: jsonb
      column: metadata_list
