Repeka\Domain\Entity\ResourceEntity:
  type: entity
  table: resource
  repositoryClass: Repeka\Application\Repository\ResourceDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    kind:
      targetEntity: Repeka\Domain\Entity\ResourceKind
      joinColumn:
        name: kind_id
        referencedColumnName: id
  fields:
    marking:
      type: jsonb
      nullable: true
    contents:
      type: jsonb
    resourceClass:
      type: string
      length: 64
      nullable: false
      column: resource_class
    displayStrategyDependencies:
      type: jsonb
      column: display_strategy_dependencies
      nullable: false
      options: {default: '{}'}
    displayStrategiesDirty:
      type: boolean
      column: display_strategies_dirty
      options: {default: true}
    pendingUpdates:
      type: jsonb
      column: pending_updates
      options: {default: '[]'}
