Repeka\Domain\Entity\ResourceKind:
  type: entity
  table: resource_kind
  repositoryClass: Repeka\Application\Repository\ResourceKindDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToOne:
    workflow:
      targetEntity: Repeka\Domain\Entity\ResourceWorkflow
      joinColumn:
        name: workflow_id
        referencedColumnName: id
  fields:
    label:
      type: json_document
      options: {jsonb: true}
    resourceClass:
      type: string
      length: 64
      nullable: false
      column: resource_class
    metadataOverrides:
      type: json_document
      options: {jsonb: true}
      column: metadata_list
    displayStrategies:
      type: json_document
      options: {jsonb: true}
      column: display_strategies
