Repeka\Domain\Entity\ResourceWorkflow:
  type: entity
  table: workflow
  repositoryClass: Repeka\Application\Repository\ResourceWorkflowDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: jsonb
    places:
      type: jsonb
      options: {default: '[]'}
    transitions:
      type: jsonb
      options: {default: '[]'}
    diagram:
      type: text
      nullable: true
    thumbnail:
      type: text
      nullable: true
    resourceClass:
      type: string
      length: 64
      nullable: false
      column: resource_class
