Repeka\Domain\Entity\UserRole:
  type: entity
  table: role
  repositoryClass: Repeka\Application\Repository\UserRoleDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: json_document
      options: {jsonb: true}
