Repeka\Domain\Entity\UserRole:
  type: entity
  table: role
  repositoryClass: Repeka\Application\Repository\UserRoleDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToMany:
    users:
      targetEntity: Repeka\Application\Entity\UserEntity
      mappedBy: userRoles
  fields:
    name:
      type: jsonb
