services:
  repository.metadata:
    class: Repeka\DataModule\Bundle\Repository\MetadataDoctrineRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [Repeka\DataModule\Domain\Entity\Metadata]

  command_handler.data.metadata_list:
    class: Repeka\DataModule\Domain\UseCase\Metadata\MetadataListQueryHandler
    autowire: true

  command_handler.data.metadata_create:
    class: Repeka\DataModule\Domain\UseCase\Metadata\MetadataCreateCommandHandler
    autowire: true

  command_validator.data.metadata_create:
    class: Repeka\DataModule\Domain\UseCase\Metadata\MetadataCreateCommandValidator
    arguments:
      - '%data_module.main_language%'
      - '%data_module.supported_controls%'
