Repeka\Application\Entity\UserEntity:
  type: entity
  table: '`user`'
  repositoryClass: Repeka\Application\Repository\UserDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    username:
      type: string
      length: 25
      unique: true
    password:
      type: string
      length: 64
    staticPermissions:
      type: json
      column: static_permissions
      options: {default: '[]'}
    email:
      type: string
      length: 60
      unique: true
    name:
      type: string
      length: 50
      nullable: true
    surname:
      type: string
      length: 50
      nullable: true
    isActive:
      type: boolean
      column: is_active
