Repeka\Application\Entity\UserEntity:
  type: entity
  table: '`user`'
  repositoryClass: Repeka\Application\Repository\UserDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  oneToOne:
    userData:
      targetEntity: Repeka\Domain\Entity\ResourceEntity
      orphanRemoval: true
      joinColumn:
        nullable: false
        name: user_data_id
        referencedColumnName: id
        onDelete: CASCADE
  fields:
    password:
      type: string
      length: 64
      nullable: true
    isActive:
      type: boolean
      column: is_active
    roles:
      type: jsonb
      options: {default: '[]'}
