Repeka\Application\Entity\UserEntity:
  type: entity
  table: '`user`'
  repositoryClass: Repeka\Application\Repository\UserDoctrineRepository
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  manyToMany:
    userRoles:
      targetEntity: Repeka\Domain\Entity\UserRole
      joinTable:
        name: user_role
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          role_id:
            referencedColumnName: id
  oneToOne:
    userData:
      targetEntity: Repeka\Domain\Entity\ResourceEntity
      joinColumn:
        nullable: false
        name: user_data_id
        referencedColumnName: id
        onDelete: CASCADE
  fields:
    username:
      type: string
      length: 25
      unique: true
    password:
      type: string
      length: 64
      nullable: true
    email:
      type: string
      length: 60
      unique: true
    isActive:
      type: boolean
      column: is_active
