services:
  repeka.event_listener.admin_panel_metrics_request:
    class: Repeka\CoreModule\Bundle\EventListener\AdminPanelMetricsRequestListener
    arguments:
      - '@m6_statsd'
      - '%admin_panel_metrics%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  kernel.event_listener.json_request_transformer:
    class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
