services:
  repeka.command_bus:
    class: Repeka\CoreModule\Bundle\Cqrs\RepekaCommandBus
    arguments:
      -
        - '@repeka.command_bus.middleware.metrics_command_bus'
        - '@repeka.command_bus.middleware.validate_command'
        - '@repeka.command_bus.middleware.wrap_command_with_transaction'
        - '@repeka.command_bus.middleware.call_command'

  repeka.command_bus.middleware.call_command:
    class: Repeka\CoreModule\Bundle\Cqrs\Middleware\CallCommandHandlerMiddleware
    autowire: true

  repeka.command_bus.middleware.wrap_command_with_transaction:
    class: Repeka\CoreModule\Bundle\Cqrs\Middleware\WrapCommandWithTransactionMiddleware
    autowire: true

  repeka.command_bus.middleware.metrics_command_bus:
    class: Repeka\CoreModule\Bundle\Cqrs\Middleware\MetricsCommandBusMiddleware
    autowire: true

  repeka.command_bus.middleware.validate_command:
    class: Repeka\CoreModule\Bundle\Cqrs\Middleware\ValidateCommandMiddleware
    autowire: true

  repeka.event_listener.admin_panel_metrics_request:
    class: Repeka\CoreModule\Bundle\EventListener\AdminPanelMetricsRequestListener
    arguments:
      - '@m6_statsd'
      - '%admin_panel_metrics%'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  kernel.event_listener.json_request_transformer:
    class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

  repeka.event_listener.csrf_request_listener:
    class: Repeka\CoreModule\Bundle\EventListener\CsrfRequestListener
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 0 }
